package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name="ADRESSE"
    ,schema="EQUIPE9"
)@XmlRootElement

public class Adresse  implements java.io.Serializable {


     private BigDecimal idadresse;
     private BigDecimal numerocivique;
     private String rue;
     private String ville;
     private String province;
     private String codepostal;
     private Set<Client> clients = new HashSet<Client>(0);
     private Set<Employe> employes = new HashSet<Employe>(0);

    public Adresse() {
    }

	
    public Adresse(BigDecimal idadresse, BigDecimal numerocivique, String rue, String ville, String province, String codepostal) {
        this.idadresse = idadresse;
        this.numerocivique = numerocivique;
        this.rue = rue;
        this.ville = ville;
        this.province = province;
        this.codepostal = codepostal;
    }
    public Adresse(BigDecimal idadresse, BigDecimal numerocivique, String rue, String ville, String province, String codepostal, Set<Client> clients, Set<Employe> employes) {
       this.idadresse = idadresse;
       this.numerocivique = numerocivique;
       this.rue = rue;
       this.ville = ville;
       this.province = province;
       this.codepostal = codepostal;
       this.clients = clients;
       this.employes = employes;
    }
   
     @Id 

    
    @Column(name="IDADRESSE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdadresse() {
        return this.idadresse;
    }
    
    public void setIdadresse(BigDecimal idadresse) {
        this.idadresse = idadresse;
    }

    
    @Column(name="NUMEROCIVIQUE", nullable=false, precision=22, scale=0)
    public BigDecimal getNumerocivique() {
        return this.numerocivique;
    }
    
    public void setNumerocivique(BigDecimal numerocivique) {
        this.numerocivique = numerocivique;
    }

    
    @Column(name="RUE", nullable=false, length=500)
    public String getRue() {
        return this.rue;
    }
    
    public void setRue(String rue) {
        this.rue = rue;
    }

    
    @Column(name="VILLE", nullable=false, length=500)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="PROVINCE", nullable=false, length=500)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="CODEPOSTAL", nullable=false, length=7)
    public String getCodepostal() {
        return this.codepostal;
    }
    
    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adresse")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adresse")
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }




}


