package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Cartecredit generated by hbm2java
 */
@Entity
@Table(name="CARTECREDIT"
    ,schema="EQUIPE9"
)@XmlRootElement

public class Cartecredit  implements java.io.Serializable {


     private String numero;
     private BigDecimal moisexpiration;
     private BigDecimal anneeexpiration;
     private String cvv;
     private String type;
     private Set<Client> clients = new HashSet<Client>(0);

    public Cartecredit() {
    }

	
    public Cartecredit(String numero, BigDecimal moisexpiration, BigDecimal anneeexpiration, String cvv, String type) {
        this.numero = numero;
        this.moisexpiration = moisexpiration;
        this.anneeexpiration = anneeexpiration;
        this.cvv = cvv;
        this.type = type;
    }
    public Cartecredit(String numero, BigDecimal moisexpiration, BigDecimal anneeexpiration, String cvv, String type, Set<Client> clients) {
       this.numero = numero;
       this.moisexpiration = moisexpiration;
       this.anneeexpiration = anneeexpiration;
       this.cvv = cvv;
       this.type = type;
       this.clients = clients;
    }
   
     @Id 

    
    @Column(name="NUMERO", unique=true, nullable=false, length=20)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="MOISEXPIRATION", nullable=false, precision=22, scale=0)
    public BigDecimal getMoisexpiration() {
        return this.moisexpiration;
    }
    
    public void setMoisexpiration(BigDecimal moisexpiration) {
        this.moisexpiration = moisexpiration;
    }

    
    @Column(name="ANNEEEXPIRATION", nullable=false, precision=22, scale=0)
    public BigDecimal getAnneeexpiration() {
        return this.anneeexpiration;
    }
    
    public void setAnneeexpiration(BigDecimal anneeexpiration) {
        this.anneeexpiration = anneeexpiration;
    }

    
    @Column(name="CVV", nullable=false, length=4)
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    
    @Column(name="TYPE", nullable=false, length=15)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cartecredit")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


