package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exemplaire generated by hbm2java
 */
@Entity
@Table(name="EXEMPLAIRE"
    ,schema="EQUIPE9"
)
public class Exemplaire  implements java.io.Serializable {


     private BigDecimal idexemplaire;
     private Film film;
     private boolean estloue;
     private Set<Location> locations = new HashSet<Location>(0);

    public Exemplaire() {
    }

	
    public Exemplaire(BigDecimal idexemplaire, boolean estloue) {
        this.idexemplaire = idexemplaire;
        this.estloue = estloue;
    }
    public Exemplaire(BigDecimal idexemplaire, Film film, boolean estloue, Set<Location> locations) {
       this.idexemplaire = idexemplaire;
       this.film = film;
       this.estloue = estloue;
       this.locations = locations;
    }
   
     @Id 

    
    @Column(name="IDEXEMPLAIRE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdexemplaire() {
        return this.idexemplaire;
    }
    
    public void setIdexemplaire(BigDecimal idexemplaire) {
        this.idexemplaire = idexemplaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFILM")
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

    
    @Column(name="ESTLOUE", nullable=false, precision=1, scale=0)
    public boolean isEstloue() {
        return this.estloue;
    }
    
    public void setEstloue(boolean estloue) {
        this.estloue = estloue;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exemplaire")
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }




}


