package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Forfait generated by hbm2java
 */
@Entity
@Table(name="FORFAIT"
    ,schema="EQUIPE9"
)@XmlRootElement

public class Forfait  implements java.io.Serializable {


     private char type;
     private BigDecimal coutparmois;
     private BigDecimal locationsmax;
     private BigDecimal dureemax;
     private Set<Client> clients = new HashSet<Client>(0);

    public Forfait() {
    }

	
    public Forfait(char type, BigDecimal coutparmois, BigDecimal locationsmax, BigDecimal dureemax) {
        this.type = type;
        this.coutparmois = coutparmois;
        this.locationsmax = locationsmax;
        this.dureemax = dureemax;
    }
    public Forfait(char type, BigDecimal coutparmois, BigDecimal locationsmax, BigDecimal dureemax, Set<Client> clients) {
       this.type = type;
       this.coutparmois = coutparmois;
       this.locationsmax = locationsmax;
       this.dureemax = dureemax;
       this.clients = clients;
    }
   
     @Id 

    
    @Column(name="TYPE", unique=true, nullable=false, length=1)
    public char getType() {
        return this.type;
    }
    
    public void setType(char type) {
        this.type = type;
    }

    
    @Column(name="COUTPARMOIS", nullable=false, precision=10)
    public BigDecimal getCoutparmois() {
        return this.coutparmois;
    }
    
    public void setCoutparmois(BigDecimal coutparmois) {
        this.coutparmois = coutparmois;
    }

    
    @Column(name="LOCATIONSMAX", nullable=false, precision=22, scale=0)
    public BigDecimal getLocationsmax() {
        return this.locationsmax;
    }
    
    public void setLocationsmax(BigDecimal locationsmax) {
        this.locationsmax = locationsmax;
    }

    
    @Column(name="DUREEMAX", nullable=false, precision=22, scale=0)
    public BigDecimal getDureemax() {
        return this.dureemax;
    }
    
    public void setDureemax(BigDecimal dureemax) {
        this.dureemax = dureemax;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="forfait")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


