package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="GENRE"
    ,schema="EQUIPE9"
)
public class Genre  implements java.io.Serializable {


     private BigDecimal idgenre;
     private String nom;
     private Set<Film> films = new HashSet<Film>(0);

    public Genre() {
    }

	
    public Genre(BigDecimal idgenre, String nom) {
        this.idgenre = idgenre;
        this.nom = nom;
    }
    public Genre(BigDecimal idgenre, String nom, Set<Film> films) {
       this.idgenre = idgenre;
       this.nom = nom;
       this.films = films;
    }
   
     @Id 

    
    @Column(name="IDGENRE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdgenre() {
        return this.idgenre;
    }
    
    public void setIdgenre(BigDecimal idgenre) {
        this.idgenre = idgenre;
    }

    
    @Column(name="NOM", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="FILMGENRE", schema="EQUIPE9", joinColumns = { 
        @JoinColumn(name="IDGENRE", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDFILM", nullable=false, updatable=false) })
    public Set<Film> getFilms() {
        return this.films;
    }
    
    public void setFilms(Set<Film> films) {
        this.films = films;
    }




}


