package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lienmedia generated by hbm2java
 */
@Entity
@Table(name="LIENMEDIA"
    ,schema="EQUIPE9"
)
public class Lienmedia  implements java.io.Serializable {


     private BigDecimal idlienmedia;
     private Film film;
     private String url;
     private String type;

    public Lienmedia() {
    }

	
    public Lienmedia(BigDecimal idlienmedia, String type) {
        this.idlienmedia = idlienmedia;
        this.type = type;
    }
    public Lienmedia(BigDecimal idlienmedia, Film film, String url, String type) {
       this.idlienmedia = idlienmedia;
       this.film = film;
       this.url = url;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="IDLIENMEDIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdlienmedia() {
        return this.idlienmedia;
    }
    
    public void setIdlienmedia(BigDecimal idlienmedia) {
        this.idlienmedia = idlienmedia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFILM")
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

    
    @Column(name="URL", length=2000)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="TYPE", nullable=false, length=15)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


