package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name="PAYS"
    ,schema="EQUIPE9"
)
public class Pays  implements java.io.Serializable {


     private BigDecimal idpays;
     private String nom;
     private Set<Film> films = new HashSet<Film>(0);

    public Pays() {
    }

	
    public Pays(BigDecimal idpays, String nom) {
        this.idpays = idpays;
        this.nom = nom;
    }
    public Pays(BigDecimal idpays, String nom, Set<Film> films) {
       this.idpays = idpays;
       this.nom = nom;
       this.films = films;
    }
   
     @Id 

    
    @Column(name="IDPAYS", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdpays() {
        return this.idpays;
    }
    
    public void setIdpays(BigDecimal idpays) {
        this.idpays = idpays;
    }

    
    @Column(name="NOM", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="payses")
    public Set<Film> getFilms() {
        return this.films;
    }
    
    public void setFilms(Set<Film> films) {
        this.films = films;
    }




}


