package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Personnage generated by hbm2java
 */
@Entity
@Table(name="PERSONNAGE"
    ,schema="EQUIPE9"
)@XmlRootElement

public class Personnage  implements java.io.Serializable {


     private PersonnageId id;
     private Film film;
     private Personne personne;
     private String nompersonnage;

    public Personnage() {
    }

	
    public Personnage(PersonnageId id, Film film, Personne personne) {
        this.id = id;
        this.film = film;
        this.personne = personne;
    }
    public Personnage(PersonnageId id, Film film, Personne personne, String nompersonnage) {
       this.id = id;
       this.film = film;
       this.personne = personne;
       this.nompersonnage = nompersonnage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfilm", column=@Column(name="IDFILM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idacteur", column=@Column(name="IDACTEUR", nullable=false, precision=22, scale=0) ) } )
    public PersonnageId getId() {
        return this.id;
    }
    
    public void setId(PersonnageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFILM", nullable=false, insertable=false, updatable=false)
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDACTEUR", nullable=false, insertable=false, updatable=false)
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }

    
    @Column(name="NOMPERSONNAGE", length=500)
    public String getNompersonnage() {
        return this.nompersonnage;
    }
    
    public void setNompersonnage(String nompersonnage) {
        this.nompersonnage = nompersonnage;
    }




}


