package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name="PERSONNE"
    ,schema="EQUIPE9"
)
public class Personne  implements java.io.Serializable {


     private BigDecimal idpersonne;
     private String nom;
     private Date datenaissance;
     private String lieunaissance;
     private Clob biographie;
     private String photourl;
     private Set<Personnage> personnages = new HashSet<Personnage>(0);
     private Set<Film> films = new HashSet<Film>(0);

    public Personne() {
    }

	
    public Personne(BigDecimal idpersonne, String nom) {
        this.idpersonne = idpersonne;
        this.nom = nom;
    }
    public Personne(BigDecimal idpersonne, String nom, Date datenaissance, String lieunaissance, Clob biographie, String photourl, Set<Personnage> personnages, Set<Film> films) {
       this.idpersonne = idpersonne;
       this.nom = nom;
       this.datenaissance = datenaissance;
       this.lieunaissance = lieunaissance;
       this.biographie = biographie;
       this.photourl = photourl;
       this.personnages = personnages;
       this.films = films;
    }
   
     @Id 

    
    @Column(name="IDPERSONNE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(BigDecimal idpersonne) {
        this.idpersonne = idpersonne;
    }

    
    @Column(name="NOM", nullable=false, length=500)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATENAISSANCE", length=7)
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="LIEUNAISSANCE", length=100)
    public String getLieunaissance() {
        return this.lieunaissance;
    }
    
    public void setLieunaissance(String lieunaissance) {
        this.lieunaissance = lieunaissance;
    }

    
    @Column(name="BIOGRAPHIE")
    public Clob getBiographie() {
        return this.biographie;
    }
    
    public void setBiographie(Clob biographie) {
        this.biographie = biographie;
    }

    
    @Column(name="PHOTOURL", length=2000)
    public String getPhotourl() {
        return this.photourl;
    }
    
    public void setPhotourl(String photourl) {
        this.photourl = photourl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personne")
    public Set<Personnage> getPersonnages() {
        return this.personnages;
    }
    
    public void setPersonnages(Set<Personnage> personnages) {
        this.personnages = personnages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personne")
    public Set<Film> getFilms() {
        return this.films;
    }
    
    public void setFilms(Set<Film> films) {
        this.films = films;
    }




}


