package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonnageId generated by hbm2java
 */
@Embeddable
public class PersonnageId  implements java.io.Serializable {


     private BigDecimal idfilm;
     private BigDecimal idacteur;

    public PersonnageId() {
    }

    public PersonnageId(BigDecimal idfilm, BigDecimal idacteur) {
       this.idfilm = idfilm;
       this.idacteur = idacteur;
    }
   


    @Column(name="IDFILM", nullable=false, precision=22, scale=0)
    public BigDecimal getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(BigDecimal idfilm) {
        this.idfilm = idfilm;
    }


    @Column(name="IDACTEUR", nullable=false, precision=22, scale=0)
    public BigDecimal getIdacteur() {
        return this.idacteur;
    }
    
    public void setIdacteur(BigDecimal idacteur) {
        this.idacteur = idacteur;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonnageId) ) return false;
		 PersonnageId castOther = ( PersonnageId ) other; 
         
		 return ( (this.getIdfilm()==castOther.getIdfilm()) || ( this.getIdfilm()!=null && castOther.getIdfilm()!=null && this.getIdfilm().equals(castOther.getIdfilm()) ) )
 && ( (this.getIdacteur()==castOther.getIdacteur()) || ( this.getIdacteur()!=null && castOther.getIdacteur()!=null && this.getIdacteur().equals(castOther.getIdacteur()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdfilm() == null ? 0 : this.getIdfilm().hashCode() );
         result = 37 * result + ( getIdacteur() == null ? 0 : this.getIdacteur().hashCode() );
         return result;
   }   


}


