package com.etsmtl.equipe9.model;
// Generated 2016-10-03 15:53:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Scenariste generated by hbm2java
 */
@Entity
@Table(name="SCENARISTE"
    ,schema="EQUIPE9"
)
public class Scenariste  implements java.io.Serializable {


     private BigDecimal idscenariste;
     private Film film;
     private String nom;

    public Scenariste() {
    }

	
    public Scenariste(BigDecimal idscenariste, String nom) {
        this.idscenariste = idscenariste;
        this.nom = nom;
    }
    public Scenariste(BigDecimal idscenariste, Film film, String nom) {
       this.idscenariste = idscenariste;
       this.film = film;
       this.nom = nom;
    }
   
     @Id 

    
    @Column(name="IDSCENARISTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdscenariste() {
        return this.idscenariste;
    }
    
    public void setIdscenariste(BigDecimal idscenariste) {
        this.idscenariste = idscenariste;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFILM")
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

    
    @Column(name="NOM", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


